valtlb379: TLB.o
	gcc -g -o valtlb379 TLB.o
	gcc -g -o heapsort heapsort.c
	gcc -g -o mergesort mergesort.c
	gcc -g -o quicksort quicksort.c

TLB.o: TLB.c
	gcc -g -c TLB.c



clean:
	rm -f *.o
	rm valtlb379
	rm heapsort
	rm quicksort
	rm mergesort